baseURL = 'https://Astharot15.github.io/'
languageCode = 'en-US'
title = 'Astharot'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

[module]
  [module.hugoVersion]
    extended = true
    min = '0.128.0'
